### ISSUE TITLE
pose_kps_00008_.png, anya.jpg and pose_dw_pose_00008_.png not available, please add that 

### ISSUE THREAD

**Issue by vijishmadhavan** [camenduru/InstantID-IPAdapter-ControlNet-jupyter#2]
pose_kps_00008_.png, anya.jpg and pose_dw_pose_00008_.png not available, please add that

**Comment by camenduru** [comment]
https://github.com/camenduru/comfyui-colab/blob/main/workflow/pose_images.zip
